export function createRunSummary(simulation) {
  const metrics = simulation.getMetrics();
  return {
    duration: metrics.tick,
    finalPopulation: metrics.livingAnts,
    maxPopulation: metrics.maxPopulation,
    foodStock: metrics.foodStock,
    foodCollected: metrics.resources,
    foodConsumed: metrics.consumedFood,
    births: metrics.births,
    deaths: metrics.deaths,
    starvationDeaths: metrics.starvationDeaths,
    environmentalDeaths: metrics.environmentalDeaths,
    dangerExposures: metrics.dangerExposures,
    dangerDistance: metrics.dangerDistance,
    averageEnergy: metrics.averageEnergy,
    seasonCyclesCompleted: metrics.seasonCyclesCompleted,
    colonyCount: metrics.colonyCount,
    foreignContacts: metrics.foreignContacts,
    contestedArea: metrics.contestedArea,
    colonies: metrics.colonies.map((colony) => ({
      id: colony.id,
      population: colony.totalPopulation,
      livingAnts: colony.livingAnts,
      foodStock: colony.foodStock,
      foodCollected: colony.resources,
      resourceShare: colony.resourceShare,
      births: colony.births,
      deaths: colony.deaths,
      territoryCells: colony.territoryCells,
      foreignContacts: colony.foreignContacts,
      averageNestDistance: colony.averageNestDistance,
    })),
    extinct: metrics.livingAnts === 0 && metrics.broodSize === 0,
  };
}
